### ISSUE TITLE
fix: all collection items must start at the same column

### ISSUE THREAD

**Issue by dargmuesli** [intlify/bundle-tools#204]
### Reporting a bug?

Why I use the yaml format in SFCs, I get the `All collection items must start at the same column` error as can be seen in the reproduction provided below.

### Expected behavior

That error does not show and the projects builds successfully.

### Reproduction

https://stackblitz.com/edit/github-a5wazj?file=app.vue,nuxt.config.ts

### Issue Package

unplugin-vue-i18n

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
```

### Additional context

Nuxt module beta1 works.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
Hi!
Thank you for your reporting!
Sorry my late response 🙇 

I checked your repro repo.
nuxtjs/i18n uses unplugin-vue-i18n internally.
Set unplugin-vue-i18n to vite plugin in your nuxt.config.ts options.
The problem with this issue is that unplugin-vue-i18n is set twice.

unplugin-vue-i18n has already configured in nuxtjs/i18n, please remove the plugin you explicitly specified if you don't need it.

Thank you for always!
