### ISSUE TITLE
Error parsing '@' character when using json5

### ISSUE THREAD

**Issue by urbgimtam** [intlify/bundle-tools#217]
### Reporting a bug?

If a translation file is in json5 format, and contains the "@", even if escaped or written as a \u0040, results in an error code 10: Invalid link format. For example, if someone uses different email addresses per locale, or an account name, etc.

Not sure if there are other characters that also break.

According to json5 documentation (https://spec.json5.org/#escapes), the '@' doesn't need to be escaped. Even if escaped, it creates the same error.

Error log:
Invalid linked format (error code: 10) in /project/sandbox/translations/en.json5
  target message: example@example.org
  target message path: anEmailString

### Expected behavior

According to json5 docs, should support the @ symbol.

### Reproduction

CodeSandBox: https://codesandbox.io/p/sandbox/determined-vaughan-5qbybf

### Issue Package

unplugin-vue-i18n

### System Info

```shell
All regular browsers.

  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 25.56 GB / 31.05 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
`@` is special character, because `@` is used in linked messages

docs says:

- linked message
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#linked-messages

- Special Characters
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters

You can avoid with literal interpolation:
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#literal-interpolation

Thanks!

**Comment by vushe** [comment]
Is there a way to disable this? In some cases translations are exposed to the customers and it's a pain to explain to e.g. business people they have to code emails as follows `{name}{'@'}{domain}{'.'}{com}`

**Comment by cozumel424** [comment]
The @ is a really bad choice to use as a special character because it's used literally everywhere in language now, not least emails and tagging like @kazupon ! 

And literal interpolation is just broken, no-one in their right mind is going to do a spaghetti mess like `{'customer'}{'-'}{'service'}{'@'}{'domain'}{'.'}{'com'}` like the example above, it's also not that flexible for different languages (which is like the whole point we're here).

Can there not be a way to either change the special character or to exclude it as in this comment https://github.com/intlify/bundle-tools/issues/53#issuecomment-1080330930

I can't be the only one with this issue. It is a great library otherwise though.

**Comment by vushe** [comment]
@cozumel424 yes agree with you. I must note, however, following started working for me: `customer-service{'@'}domain.com`
In any case, I can't provide it to translators.
